### ISSUE TITLE
[Pathway] R-E-S-P-E-C-T

### ISSUE THREAD

**Issue by thornet** [mozilla/mozfest-program#2]
A proposed pathway that focuses on the experiences of people marginalized online. This pathway will include chats with women who have been victims of vicious online attacks (think Gamergate), a working session with an Open Web Fellow building an interactive experience around the Feminist Principles of the Internet, a look at ethical practices, including handling data -- with the BBC --, a hacking session with an Open Web Fellow who is analyzing data around police discrimination practices in racially segregated neighborhoods, a teaching/learning session with Violet Blue’s Smart Girls’ Guide to Online Privacy, and even a panel/Q&A session about women’s safety online, including those who have been victimized through revengeporn.

Sessions include:
- [ ] #8 Experiences of race, ethnicity and authoritarian governments
- [ ] #7 Experiences of women
- [ ] #6 Risks of internet mob justice
